CREATE TABLE PRODUCTO 
(
  ID NUMBER  NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  CANTIDAD INT NOT NULL,
  PRECIO NUMBER(9, 2) NOT NULL,
  PRECIO_VENTA NUMBER(9, 2) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCTO;


INSERT INTO PRODUCTO(ID,NOMBRE,CANTIDAD,PRECIO, PRECIO_VENTA) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Doritos barbacoa','4','3.5','9');